Updated to detect if hnu is directly run from the source tree.

diff --git a/scripts/hnu b/scripts/hnu
--- a/scripts/hnu
+++ b/scripts/hnu
@@ -31,5 +31,18 @@ else
   fi
   PHOTON="$INCDIR/photon.php"
 fi
+# Now, we test if $PHOTON is correctly available, if
+# not, hnu may have been called directly from the source
+# tree, so we try to find photon.php
+if [ ! -f $PHOTON ]; then
+    HNU=`readlink -f $0`
+    HNUDIR=`dirname $HNU`
+    PHOTON=`readlink -f "$HNUDIR/../src/photon.php"`
+    if test "x$PHOTON" = "x"; then
+	echo "[ERROR] Unable to find photon.php. Check your installation."
+	exit 1
+    fi
+    echo "[INFO] Running with photon.php from the source installation."
+fi
 
 exec $PHP $PHOTON "$@"
